version: '3'

services:
  api:
    build: .
    image: fast_and_furious_api:latest
    container_name: web
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:alpine
    container_name: postgres_database
    ports:
      - '6500:5432'
    restart: always
    env_file:
      - ./.env
    volumes:
      - data:/data/db
volumes:
  data: